In [2]:
from copy import deepcopy
import numpy as np

In [3]:
discount_factor = 0.9
A = (0, 1)
B = (0, 3)
A1 = (4, 1)
B1 = (2, 3)
n = 5
actions = [(0, -1), (-1, 0), (0, 1), (1,0)]

In [4]:
"""
* Iterative Value evaluation
"""

grid = np.zeros((n, n))

delta = 1e-4
diff = 1000
while diff > delta:
    updated_grid = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            maxvalue = 0
            for action in actions: # four actions possible
                if (i,j) == A: # Give priority to A and B since all moves are valid here regardless of bounds
                    reward = 10.0
                    x,y = A1
                elif (i,j) == B:
                    reward = 5.0
                    x,y = B1
                elif i + action[0] < 0 or i + action[0] >= n or j + action[1] < 0 or j + action[1] >= n: # Check bounds after checking for A and B
                    reward = -1.0
                    x,y = i,j
                else:
                    reward = 0
                    x,y = i + action[0], j + action[1]
                # Bellman's equation
                maxvalue = max(maxvalue, (reward + discount_factor * (grid[x, y])))
            updated_grid[i, j] += maxvalue
    diff = np.abs(np.sum(np.subtract(updated_grid, grid)))
    grid = updated_grid

In [5]:
print (grid)

[[21.97744338 24.41938153 21.97744338 19.41938153 17.47744338]
 [19.77969904 21.97744338 19.77969904 17.80172914 16.02153504]
 [17.80172914 19.77969904 17.80172914 16.02153504 14.41938153]
 [16.02153504 17.80172914 16.02153504 14.41938153 12.97744338]
 [14.41938153 16.02153504 14.41938153 12.97744338 11.67969904]]
